### ISSUE TITLE
<spring-board> should have a :host display style of block

### ISSUE THREAD

**Issue by rdmurphy** [rdmurphy/spring-board-element#5]
This risks dipping into Spring '83 spec territory, but in my limited experience I've yet to find a reason for `<spring-board>` to not default to `display: block`. 🤔 Setting `width`, `height` and `background-color` on the element doesn't really work out the box otherwise.

**Comment by robinsloan** [comment]
This ought to be in the specification -- I will add it to the client section of the new draft. (Honestly, I always forget that custom elements don't have `display: block` set; and this has caused me problems in the past!)

**Comment by rdmurphy** [comment]
Ooh, okay! This this should most certainly happen. 🙌
