### ISSUE TITLE
Love it! Thank you.

### ISSUE THREAD

**Issue by rpj** [rdmurphy/spring-board-element#7]
Hello, another Ryan! 😄👋 

First of all, I have to say I absolutely _love_ this idea & project. Thank you a million for putting it together, it's a genuinely novel & lovely addition to the Spring-o-sphere, and one I'm _certain_ will have users... as I'm already in need of it! I really want to toss my current embedding code and use this everywhere instead.

**Comment by rdmurphy** [comment]
Hello to you as well, other Ryan! 😄 Thank you so much! I appreciate the kind words.

I did see what the issue originally was and I got really worried, hah, but I'm guessing you might have found the same info — when `innerHTML` injects `<script>` tags they are rendered inert per the HTML5 spec. I do appreciate how `DOMParser` neatly strips them though. 😅

I agree that in the long term we should run away from `innerHTML` — with the need to query the board HTML for `<time>` and `<meta>` elements before it's injected into the Shadow DOM it'll definitely be more robust to create a `template` on the fly or prep via `DOMParser`.

**Comment by rpj** [comment]
Hahaha you got it _exactly_ right, I was digging into it further after I realized I'd made a change that necessitated I use it and found precisely what you did. _Then_ I got really worried I might've caused unnecessary concern with my issue (which it turns out I did!) so I hastily edited it to remove any mention of that, to try and assuage that concern ASAP. My sincere apologies for that! Thank you again for this, it's genuinely fantastic.

**Comment by rdmurphy** [comment]
Hah, no worries at all! I think something like that is _definitely_ worth being certain about and it didn't even cross my mind to check, so I feel better knowing we're in the clear. 🙌

That MDN section did remind me just how important it is to have the `script-src` CSP header/meta tag — neither `innerHTML` nor `DOMParser` will prevent inline event declarations like `<h1 onclick="<bad js">Maybe click here</h1>`. The script in that callback would run without it! 😬
